In [55]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [225]:
with open("/home/peter/Downloads/AdventOfCode/day15Input.txt") as fh:
    lines = fh.readlines()
#with open("/home/peter/Downloads/AdventOfCode/day15Test.txt") as fh:
#    lines = fh.readlines()


In [226]:
def npFromLines(lines):
    board = np.zeros(shape=(len(lines),len(lines[0].strip())),dtype=np.int32)
    for i in range(len(lines)):
        for j in range(len(lines[i].strip())):
            board[i][j] = int(lines[i][j])
    return board
board = npFromLines(lines)

realBoard = np.zeros(shape=(board.shape[0]*5,board.shape[0]*5),dtype=np.int32)
for i in range(realBoard.shape[0]):
    for j in range(realBoard.shape[1]):
        baseVal = board[i%board.shape[0],j%board.shape[1]]
        distI = i//board.shape[0]
        distJ = j//board.shape[1]
        baseVal += distI + distJ
        baseVal = baseVal%9
        if baseVal == 0:
            baseVal = 9
        realBoard[i,j] = baseVal
board = realBoard

In [227]:
print(np.max(realBoard))

9


In [228]:
paths = np.zeros(shape=(board.shape[0],board.shape[1]),dtype=np.int32)
for el in range(len(paths)):
    paths[el] = 1000000000
paths[0,0] = 0



def getMinNeighbor(board,paths,point):
    x,y = point
    val = board[x,y]
    minSoFar = 10000000
    #print(point)
    if x > 0:
        tmp = val + paths[x-1,y]
        minSoFar = min(tmp,minSoFar)
     #   print(minSoFar)
        
    if y > 0:
        tmp = val + paths[x,y-1]
        minSoFar = min(tmp,minSoFar)
      #  print(minSoFar)
    if x+1 < board.shape[0]:
        tmp = val + paths[x+1,y]
        minSoFar = min(tmp,minSoFar)
       # print(minSoFar)
    if y+1 < board.shape[1]-1:
        tmp = val + paths[x,y+1]
        minSoFar = min(tmp,minSoFar)
        #print(minSoFar)
    #print(type(minSoFar))
    #print(type(paths[x,y]))
    if minSoFar < paths[x,y]:
        #print("changed ",paths[x,y]," to ", minSoFar)
        paths[x,y] = minSoFar
        return 1
    else: 
        #print("not changed on point",point)
        return 0

# return list of points within board neighboring the input
def getNeighbors(board,point):
    x,y = point
    points = []
    if x > 0:
        points.append((x-1,y))
    if y > 0:
        points.append((x,y-1))
    if x < board.shape[0]-1:
        points.append((x+1,y))
    if y < board.shape[1]-1:
        points.append((x,y+1))
    return points
    
    
updatedPoints = set()
updatedPoints.add((0,0))
while len(updatedPoints) > 0:
#if 1:
    newSet = set()
    for point in updatedPoints:
        newSet.update(getNeighbors(board,point))
    updatedPoints = set()
    for point in newSet:
        if getMinNeighbor(board,paths,point) == 1:
            updatedPoints.add(point)
    print("size of updated Points is ", len(updatedPoints))
    #viz = np.zeros(shape=(board.shape[0],board.shape[1]))
    #for point in updatedPoints:
    #    viz[point] = 1
    #    plt.imshow(viz)

size of updated Points is  2
size of updated Points is  3
size of updated Points is  4
size of updated Points is  5
size of updated Points is  7
size of updated Points is  8
size of updated Points is  9
size of updated Points is  10
size of updated Points is  12
size of updated Points is  13
size of updated Points is  16
size of updated Points is  17
size of updated Points is  18
size of updated Points is  21
size of updated Points is  25
size of updated Points is  27
size of updated Points is  30
size of updated Points is  29
size of updated Points is  31
size of updated Points is  34
size of updated Points is  37
size of updated Points is  37
size of updated Points is  39
size of updated Points is  42
size of updated Points is  46
size of updated Points is  50
size of updated Points is  51
size of updated Points is  52
size of updated Points is  55
size of updated Points is  57
size of updated Points is  62
size of updated Points is  67
size of updated Points is  70
size of updated P

In [229]:
print(updatedPoints)

set()


In [230]:
if 1:
    newSet = set()
    for point in updatedPoints:
        newSet.update(getNeighbors(board,point))
    updatedPoints = set()
    for point in newSet:
        if getMinNeighbor(board,paths,point) == 1:
            updatedPoints.add(point)
    viz = np.zeros(shape=(board.shape[0],board.shape[1]))
    for point in updatedPoints:
        viz[point] = 1
        plt.imshow(viz)

In [231]:
print(paths)

[[   0    4   13 ... 1692 1694 1703]
 [   7    6   12 ... 1684 1690 1699]
 [  12    7   16 ... 1684 1688 1690]
 ...
 [1704 1706 1697 ... 2879 2887 2888]
 [1708 1707 1701 ... 2880 2886 2888]
 [1714 1706 1704 ... 2886 2894 2893]]


In [232]:
print(paths.shape)

(500, 500)


In [224]:
print(board)

[[1 1 6 ... 2 8 6]
 [1 3 8 ... 1 2 6]
 [2 1 3 ... 7 6 3]
 ...
 [7 5 6 ... 5 2 8]
 [5 6 4 ... 4 1 9]
 [6 7 5 ... 4 7 9]]
