In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [2]:
lines = """start-kc
pd-NV
start-zw
UI-pd
HK-end
UI-kc
pd-ih
ih-end
start-UI
kc-zw
end-ks
MF-mq
HK-zw
LF-ks
HK-kc
ih-HK
kc-pd
ks-pd
MF-pd
UI-zw
ih-NV
ks-HK
MF-kc
zw-NV
NV-ks"""

with open("/home/peter/Downloads/AdventOfCode/day11Input.txt") as fh:
    lines = fh.readlines()

In [3]:
def npFromLines(lines):
    board = np.zeros(shape=(len(lines),len(lines[0].strip())),dtype=np.int32)
    for i in range(len(lines)):
        for j in range(len(lines[i].strip())):
            board[i][j] = int(lines[i][j])
    return board
board = npFromLines(lines)

In [4]:
print(board)

[[6 6 1 7 1 1 3 5 8 4]
 [6 5 4 4 2 1 8 6 3 8]
 [5 4 5 7 3 3 1 4 8 8]
 [1 1 3 5 6 7 5 5 8 7]
 [1 2 2 1 3 5 3 2 1 6]
 [1 8 1 1 1 2 4 3 7 8]
 [1 3 8 7 8 6 4 3 6 8]
 [4 4 2 7 6 3 7 2 6 2]
 [6 7 7 8 6 4 5 4 8 6]
 [3 6 8 2 1 4 6 7 4 5]]


In [5]:
directions = [
    (-1,-1),
    (-1, 0),
    ( 0,-1),
    ( 1,-1),
    (-1, 1),
    ( 0, 1),
    ( 1, 0),
    ( 1, 1),
]

In [6]:
def insideBoard(loc,board):
    if loc[0] >= 0 and loc[0] < board.shape[0] and \
        loc[1] >= 0 and loc[1] < board.shape[1]:
            return True
    else:
        return False

      

In [24]:
def updateNeighbors(loc,board):
    for d in directions:
        nloc = (loc[0]+d[0],loc[1]+d[1])
        #print(nloc)
        if insideBoard(nloc,board):
            board[nloc] += 1
    return board
flashCount = 0
def flash(board):
    localFlashCount = 0
    changed = True
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            loc = (i,j)
            board[loc] += 1
    while changed:
        changed = False
        for i in range(board.shape[0]):
            for j in range(board.shape[1]):
                loc = (i,j)
                if board[loc] > 9:
                    localFlashCount += 1
                    board = updateNeighbors(loc,board)
                    board[loc] = -1000
                    changed = True
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            loc = (i,j)
            if board[loc] < 0:
                board[loc] = 0
    return (board,localFlashCount)

In [25]:
foo = np.array((3, 5))
print(board[foo[0],foo[1]])

8


In [44]:
board = npFromLines(lines)
flashCount = 0
itterCount = 0
def isAllZero(board):
    allZero = True
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            loc = (i,j)
            if board[loc] != 0:
                allZero = False
    return allZero

while not isAllZero(board):
    itterCount += 1
    board,locFlash = flash(board)
    flashCount += locFlash

In [45]:
print(flashCount)

6551


In [46]:
print(itterCount)

418


In [47]:
print(board)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
