In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy
import math
import time

In [11]:
with open("/home/peter/Downloads/AdventOfCode/day25Input.txt") as fh:
    lines = fh.readlines()
#with open("/home/peter/Downloads/AdventOfCode/day25Test.txt") as fh:
#    lines = fh.readlines()


In [12]:
def npFromLines(lines):
    board = np.zeros(shape=(len(lines),len(lines[0].strip())),dtype=np.int16)
    for i in range(len(lines)):
        for j in range(len(lines[i].strip())):
            val = 0
            if lines[i][j] == ">":
                val = 1
            elif lines[i][j] == "v":
                val = 4
            board[i][j] = val
    return board
board = npFromLines(lines)


In [13]:
def update(board):
    changed = False
    # do east
    # east = 1
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            # j is east
            nextv = j+1 if j < board.shape[1]-1 else 0
            if board[i,nextv] == 0:
                changed = True
                board[i,nextv] = 1
                board[i,j] = -1
    board[board==-1] = 0
    
    # do south
    for i in range(board.shape[0]):
        nextv = i+1 if i < board.shape[0]-1 else 0
        for j in range(board.shape[1]):
            # j is east
            if board[nextv,j] == 0:
                changed = True
                board[nextv,j] = 1
                board[i,j] = -1
    board[board==-1] = 0
    return board,changed

def take2(board):
    # do east
    first = np.roll(board,1,axis=1)
    mask = (first == 1) & (board == 0)
    changed = mask.any()
    board[mask] = 1
    board[np.roll(mask,-1,axis=1)] = 0
    
    # do south
    first = np.roll(board,1,axis=0)
    mask = (first == 4) & (board == 0)
    board[mask] = 4
    board[np.roll(mask,-1,axis=0)] = 0
    changed |= mask.any()
    return board,changed

In [14]:
board = npFromLines(lines)
print(board[0:5,0:5])
first = np.roll(board[0:5,0:5],1,axis=1)
second = board[0:5,0:5]
#first == 1 && second == 0
print((np.roll(board[0:5,0:5],1,axis=1)==1) & (board[0:5,0:5] == 0))


[[0 0 4 0 4]
 [4 1 1 0 1]
 [0 4 0 1 0]
 [1 0 0 0 4]
 [1 4 4 1 0]]
[[False False False False False]
 [False False False  True False]
 [False False False False  True]
 [False  True False False False]
 [False False False False  True]]


In [15]:
board = npFromLines(lines)
i = 0
changed = True
print(board)
#for i in range(60):
while changed:
    board,changed = take2(board)
    i += 1
    if i > 500:
        print("i ==",i)
        print(board)
        print(changed)
    if (i % 100 == 0):
        print("i ==",i)
print("finished part two")
print("final i was ",i)



[[0 0 4 ... 1 1 0]
 [4 1 1 ... 1 0 0]
 [0 4 0 ... 0 4 0]
 ...
 [0 4 4 ... 0 0 0]
 [4 0 1 ... 1 4 0]
 [4 1 0 ... 0 0 4]]
i == 100
i == 200
i == 300
finished part two
final i was  374


In [7]:
board[1,0]

0

In [8]:
foo = board==1
print(foo)
board[foo].shape
board[foo] = 100

[[False False  True  True False  True False False False False]
 [False False False False  True  True False False False False]
 [False False  True  True False  True  True False False False]
 [False False  True  True  True  True  True False False False]
 [False False False False False False False  True False False]
 [False  True False False False False False  True  True False]
 [False False False False False False False False  True  True]
 [ True False False False False False False False False  True]
 [False  True False False False False False False False False]]


In [9]:
board

array([[  0,   0, 100, 100,   4, 100,   4,   4,   0,   0],
       [  0,   0,   4,   0, 100, 100,   4,   4,   0,   0],
       [  0,   0, 100, 100,   4, 100, 100,   4,   4,   0],
       [  0,   0, 100, 100, 100, 100, 100,   4,   4,   0],
       [  4,   0,   0,   0,   0,   0,   0, 100,   4,   4],
       [  4, 100,   4,   0,   0,   0,   0, 100, 100,   4],
       [  4,   4,   4,   0,   0,   0,   0,   0, 100, 100],
       [100,   4,   4,   0,   0,   0,   0,   0,   0, 100],
       [  0, 100,   4,   0,   4,   4,   0,   4,   0,   0]], dtype=int16)