In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy
import math

In [2]:
with open("/home/peter/Downloads/AdventOfCode/day20Input.txt") as fh:
    lines = fh.readlines()
#with open("/home/peter/Downloads/AdventOfCode/day20Test.txt") as fh:
#    lines = fh.readlines()


In [23]:
def npFromLines(lines):
    board = np.zeros(shape=(len(lines)+112,len(lines[0].strip())+112),dtype=np.int32)
    for i in range(len(lines)):
        for j in range(len(lines[i].strip())):
            board[i+55][j+55] = 1 if lines[i][j] == "#" else 0
    return board
board = npFromLines(lines[2:])
enhance = lines[0]

In [24]:
print(board.shape)
#print(new.shape[0])

(212, 212)


In [25]:

for asdf in range(50):
    new = np.zeros(shape=(len(lines)+110,len(lines[2].strip())+110),dtype=np.int32)
    for i in range (0,new.shape[0],1):
        for j in range(0,new.shape[1],1):
            if i == 0 or j == 0 or i == new.shape[0]-1 or j == new.shape[1]-1:
                new[i,j] = (asdf ^ 1) & 1
                continue
            #print("i ",i," j ",j)
            foo = board[i-1:i+2,j-1:j+2]
            #print(foo)
            #if np.count_nonzero(foo) > 0:
            #    print(foo)
            bar = np.reshape(foo,newshape=9)
            #if np.count_nonzero(foo) > 0:
            #    print(bar)
            val = 0
            for b in bar:
                val = val*2 + b
            #if np.count_nonzero(foo) > 0:
            #    print(val)
            v = 1 if enhance[val] == "#" else 0
            #if np.count_nonzero(foo) > 0:
            #    print(v)
            new[i,j] = v
    print(board)
    board = new
print(np.count_nonzero(board[2:-3,2:-3]))
print(board)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [6]:
biz = board[20:23,20:23]
bap = np.reshape(board[20:23,20:23],newshape=9)

In [7]:
b = 0
for i in bap:
    b = b*2 + i

In [8]:
print(enhance[2])
print(board[-10:,-10:])

#
[[0 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [1 1 1 1 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [9]:
# not 5710
print(np.count_nonzero(board[5:115,5:115]))

5913


In [11]:
# not 19606
# not 21169
print(board[:10,:10])

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 1 0 0]
 [0 0 1 1 1 1 0 0 1 1]
 [0 1 0 1 0 0 0 0 0 1]
 [0 0 1 1 0 1 0 1 0 1]
 [0 0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 0 1 1 1]
 [0 1 1 0 1 0 0 0 1 1]
 [0 1 0 0 0 0 0 0 1 0]
 [0 1 1 1 1 1 1 1 0 0]]
