In [1]:
import numpy as np

In [2]:
with open("/home/peter/Downloads/AdventOfCode/day4Input.txt") as fh:
    lines = fh.readlines()

In [3]:
testInput = """
"""
alines = testInput.split("\n")
def getBoards(lines):
    boards = np.zeros(shape=(100,2,5,5),dtype= np.int32)
    random_numbers = lines[0]
    count = -1;
    boardNum = -1;
    for line in lines[1:]:
        if count == -1:
            boardNum+=1
            # new board, empty line, no content
        else:
            row = np.array([int(x) for x in line.split()])
            boards[boardNum][0][count] = row
        count+=1
        if count >= 5:
            count = -1
    return boards

In [7]:
foo = np.zeros(shape=(5,5))
random_numbers = lines[0]

In [8]:
foo[0] = np.array([int(x) for x in lines[2].split()])

In [9]:
numbers = [int(x) for x in random_numbers.split(",")]

In [10]:
def updateBoards(ranNum, boards):
    for board in boards:
        # each board:
        #print("starting board")
        for rowNum in range(5):
            #print("row is ",board[0][rowNum])
            for colNum in range(5):
                #print("col is ", board[0][rowNum][colNum])
                el = board[0][rowNum][colNum]
                if el == ranNum:
                    #print("matched", el, ranNum)
                    board[1][rowNum][colNum] = 1

In [11]:
def checkCol(board):
    for row in range(5):
        for col in range(5):
            if board[1][row][col] != 1:
                break
            if col == 4:
                return True
    return False

def checkRow(board):
    for col in range(5):
        for row in range(5):
            if board[1][row][col] != 1:
                break
            if row == 4:
                return True
    return False

def checkDia(board):
    for x in range(5):
        if board[1][x][x] != 1:
            break
        if x == 4:
            return True
    for x in range(5):
        if board[1][x][4-x] != 1:
            break
        if x == 4:
            return True
    return False
    
def checkBoards(boards):
    #check boards for wins:
    index = 0
    for board in boards:
        win = False
        #check col
        win |= checkCol(board)
        #check row
        win |= checkRow(board)
        #check diagonal
        win |= checkDia(board)
        if win:
            return board,index
        index+=1
    return (None,None)

In [14]:
boards = getBoards(lines)
winner = None
for num in numbers:
    updateBoards(num, boards)
    winner, index = checkBoards(boards)
    #if winner is not None and boards.shape[0] < 3:
     #   break
    while winner is not None:
        lastWinner = winner
        # remove that index from boards
        #print(boards.shape)
        boards = np.delete(boards,index,axis=0)
        # find the next winner
        winner, index = checkBoards(boards)
    print(boards.shape)
    print(num)
    #if boards.shape[0] == 1:
        #break

(100, 2, 5, 5)
42
(100, 2, 5, 5)
44
(100, 2, 5, 5)
71
(100, 2, 5, 5)
26
(100, 2, 5, 5)
70
(100, 2, 5, 5)
92
(100, 2, 5, 5)
77
(100, 2, 5, 5)
45
(100, 2, 5, 5)
6
(100, 2, 5, 5)
18
(100, 2, 5, 5)
79
(100, 2, 5, 5)
54
(100, 2, 5, 5)
31
(100, 2, 5, 5)
34
(100, 2, 5, 5)
64
(100, 2, 5, 5)
32
(100, 2, 5, 5)
16
(100, 2, 5, 5)
55
(100, 2, 5, 5)
81
(100, 2, 5, 5)
11
(100, 2, 5, 5)
90
(100, 2, 5, 5)
10
(99, 2, 5, 5)
21
(99, 2, 5, 5)
87
(99, 2, 5, 5)
0
(99, 2, 5, 5)
84
(98, 2, 5, 5)
8
(98, 2, 5, 5)
23
(98, 2, 5, 5)
1
(98, 2, 5, 5)
12
(96, 2, 5, 5)
60
(95, 2, 5, 5)
20
(95, 2, 5, 5)
57
(93, 2, 5, 5)
68
(92, 2, 5, 5)
61
(92, 2, 5, 5)
82
(92, 2, 5, 5)
49
(91, 2, 5, 5)
59
(88, 2, 5, 5)
22
(87, 2, 5, 5)
2
(86, 2, 5, 5)
63
(86, 2, 5, 5)
33
(86, 2, 5, 5)
50
(84, 2, 5, 5)
39
(83, 2, 5, 5)
28
(83, 2, 5, 5)
30
(83, 2, 5, 5)
88
(79, 2, 5, 5)
41
(78, 2, 5, 5)
69
(77, 2, 5, 5)
72
(74, 2, 5, 5)
98
(72, 2, 5, 5)
73
(69, 2, 5, 5)
7
(67, 2, 5, 5)
65
(63, 2, 5, 5)
53
(61, 2, 5, 5)
35
(57, 2, 5, 5)
96
(55, 2, 5, 5)
6

In [16]:
print(lastWinner)


[[[ 1 27 74 89  4]
  [29  9 78 48 54]
  [10 38 13 40 49]
  [71 73 79 77 17]
  [25 22 91 20  2]]

 [[ 1  1  1  0  1]
  [ 1  1  0  0  1]
  [ 1  0  0  1  1]
  [ 1  1  1  1  0]
  [ 1  1  1  1  1]]]


In [ ]:
print(numbers)

In [17]:
print(lastWinner)
winner = lastWinner

[[[ 1 27 74 89  4]
  [29  9 78 48 54]
  [10 38 13 40 49]
  [71 73 79 77 17]
  [25 22 91 20  2]]

 [[ 1  1  1  0  1]
  [ 1  1  0  0  1]
  [ 1  0  0  1  1]
  [ 1  1  1  1  0]
  [ 1  1  1  1  1]]]


In [18]:
sum = 0
for i in range(5):
    for j in range(5):
        if winner[1][i][j] == 0:
            sum += winner[0][i][j]
print(sum)

283


In [19]:
283*25


7075

In [ ]:
print(lastWinner)

In [ ]:
print(len(boards))

In [ ]:
blah = np.delete(blah,2,axis=0)
print(len(blah))

In [ ]:
print(blah)